[package]
org = "ballerinax"
name = "moesif_server_tests"
version = "0.1.0"
distribution = "2201.12.8"

[build-options]
observabilityIncluded = true

[[dependency]]
org="ballerinax"
name="moesif"
repository="local"
version = "@toml.version@"
