name: PR Build

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.run_id }}
  cancel-in-progress: true

on: pull_request

jobs:
  steps:
    - name: Set up Ballerina
      uses: ballerina-platform/setup-ballerina@v1.1.3
      with:
        version: ${{ env.BALLERINA_DISTRIBUTION_VERSION }}
  call_workflow:
    name: Run PR Build Workflow
    if: ${{ github.repository_owner == 'ballerina-platform' }}
    uses: ballerina-platform/ballerina-library/.github/workflows/pull-request-build-template.yml@main
    secrets: inherit
